---
title: Test Site One
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Terrance Gallaher Jr
bio: UX Designer, Web Designer, I Mostly roam around the PNW looking for good food  and
  people.
description: A portfolio website and a place to follow my super cool blog!
external-image: false
picture: assets/images/profile.jpg
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
twitter: NivedithaRam
github: https://github.com/terranceleeg
email: terranceleeg@gmail.com
authors:
  terranceleeg:
    name: Terrance Gallaher Jr
    bio: UX Designer, Web Designer, I Mostly roam around the PNW looking for good
      food  and people.
    external-image: false
    picture: assets/images/profile.jpg
    github: https://github.com/terranceleeg
width: large
research: true
teaching: true
about: true
blog: true
read-time: true
show-tags: true
related: true
blog-nav-links: true
show-author: true
animation: true
sass:
  sass_dir: _sass
  style: compressed
gems:
- jemoji
- jekyll-mentions
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- indigo-gh-pages.zip
- Rakefile
- screen-shot.png
- travis.sh
- tasks
