---
title: Test Site One
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Terrance Gallaher
bio: Physics, Teaching, Engineering.
description: A blog about Physics and teaching science
external-image: false
picture: assets/images/profile.jpg
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
twitter: NivedithaRam
github: NivedithaRam
email: niveditha.ramasubramanian@stonybrook.edu
authors:
  NivedithaRam:
    name: Niveditha Ram
    bio: Physics, Reading, Teaching.
    external-image: false
    picture: assets/images/profile.jpg
    twitter: NivedithaRam
width: large
research: true
teaching: true
about: true
blog: true
read-time: true
show-tags: true
related: true
blog-nav-links: true
show-author: true
animation: true
sass:
  sass_dir: _sass
  style: compressed
gems:
- jemoji
- jekyll-mentions
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- indigo-gh-pages.zip
- Rakefile
- screen-shot.png
- travis.sh
- tasks
